version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    # Não é necessário mapear a porta para o host, pois a API se comunicará
    # pela rede interna do Docker.

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # A API se conecta ao banco de dados usando o nome do serviço 'db' como host
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db

volumes:
  # Define um volume nomeado para persistir os dados do PostgreSQL
  postgres_data:

